version: "3"
services:
  mysql:
    container_name: compras_db
    image: mysql:5.7
    ports:
      - "3301:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "compras"
